# configs/sac/checkpoint3.yaml
experiment_name: checkpoint3_sac_weak
seed: 0

# Environment
env_name: Hockey-v0
mode: NORMAL
opponent: weak
reward_shaping:
  touch_puck: 0.1
  puck_direction: 0.2
  closeness_to_puck: 0.0

# Agent
agent_type: sac
gamma: 0.97
tau: 0.005

# SAC-specific params
hidden_dim: 256
actor_lr: 0.0003
critic_lr: 0.0003
alpha: 0.2

# Training
total_timesteps: 500000
learning_starts: 10000
batch_size: 256
replay_capacity: 1000000

log_dir: ./logs
